apiVersion: v1
kind: Service
metadata:
  labels:
    app: bantay-api
  name: bantay-api
  namespace: dev
spec:
  ports:
  - name: predict
    port: 5000
    targetPort: 5000
  selector:
    app: bantay-api
  type: LoadBalancer
